server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: false

tenant:
  datasource:
    tenant1:
      url: jdbc:postgresql://localhost:5432/tenant1_db
      username: tenant1_user
      password: tenant1_pass
      driver-class-name: org.postgresql.Driver
    tenant2:
      url: jdbc:postgresql://localhost:5433/tenant2_db
      username: tenant2_user
      password: tenant2_pass
      driver-class-name: org.postgresql.Driver